spring:
  application:
    name: eu5map
#  h2:
#    console:
#      enabled: true  # Веб-консоль H2 на http://localhost:8080/h2-console
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:mem:eu5map